# Configurações do servidor
server:
  port: 8080
  servlet:
    context-path: /api

# Configurações da aplicação
spring:
  application:
    name: API de Classificação de E-mails com IA Real
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

# Configurações de logging
logging:
  level:
    br.com.techcorp: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Configurações da API
api:
  version: "1.0.0"
  description: "API de Classificação de E-mails com IA Real usando Spring Boot"
  endpoints:
    base: "/api"
    classificacao: "/classificar"
    health: "/health"
    modelo: "/modelo"

# Configurações da IA
ai:
  nome: "IA Real Hugging Face"
  versao: "1.0"
  tipo: "Transformers + Deep Learning"
  precisao: 0.92
  tecnologia: "Hugging Face + DJL + PyTorch"
  bibliotecas:
    - "DJL (Deep Java Library)"
    - "PyTorch Engine"
    - "HuggingFace Tokenizers"
    - "Transformers"
  modelo:
    nome: "microsoft/mdeberta-v3-base"
    engine: "PyTorch"
    suporte: "Multilíngue (inclui português)"
    maxLength: 512
    cache: true
    fallback: true
